---
- name: "install_undercloud | directory images"
  file:
    path: "/home/{{ ostackuser }}/images"
    state: directory

- name: "install_undercloud | directory templates"
  file:
    path: "/home/{{ ostackuser }}/templates"
    state: directory

- name: "install_undercloud | "
  shell: "hostnamectl set-hostname {{ fqdn }}"
  become: True

- name: "install_undercloud | "
  shell: "hostnamectl --transient set-hostname {{ fqdn }}"
  become: True