---
- name: "install_undercloud | directory images"
  file:
    path: "/home/{{ ostackuser }}/images"
    state: directory

- name: "install_undercloud | directory templates"
  file:
    path: "/home/{{ ostackuser }}/templates"
    state: directory


- name: Mount an NFS volume
  ansible.posix.mount:
    src: 10.1.0.106:/images
    path: /images
    opts: rw,sync,soft,intr
    state: mounted
    fstype: nfs

- name: Mount an NFS volume
  ansible.posix.mount:
    src: 10.1.0.106:/templates
    path: /templates
    opts: rw,sync,soft,intr
    state: mounted
    fstype: nfs

- name: "install_undercloud| Create undercloud.conf"
  ansible.builtin.template:
    src: undercloud.conf.j2
    dest: "/home/{{ ostackuser }}/undercloud.conf"
    owner: stack
    group: stack
    mode: '0600'

- name: "install_undercloud| Create containers-prepare-parameter.yaml"
  ansible.builtin.template:
    src: containers-prepare-parameter.yaml.j2
    dest: "/home/{{ ostackuser }}/containers-prepare-parameter.yaml"
    owner: stack
    group: stack
    mode: '0600'

