---
- name: "install_undercloud | directory images"
  file:
    path: "/home/{{ ostackuser }}/images"
    state: directory

- name: "install_undercloud | directory templates"
  file:
    path: "/home/{{ ostackuser }}/templates"
    state: directory

- name: "install_undercloud| Create undercloud.conf"
  ansible.builtin.template:
    src: undercloud.conf.j2
    dest: "/home/{{ ostackuser }}"
    owner: stack
    group: stack
    mode: '0600'
    
