---
- name: "main | Include OS-specific variables."
  include_vars: "{{ ansible_os_family }}.yml"

- name: "main | Installing pre dependencies of xorg-server"
  include: "{{ ansible_os_family }}.yml"

- name: "main | template "
  include: "template.yml" 