---
# This task installs pre dependencies of xorg
- name: "install_undercloud |  Register rhel"
  shell: "subscription-manager register --org=6207854 --activationkey=GEC-RHOSP-KEY"
  become: True

- name: "install_undercloud | set hostname --transient "
  shell: "subscription-manager attach --pool={{ ostack_pool }}"
  become: True

