---
# This task installs pre dependencies of xorg
- name: "install_undercloud | Set hostname "
  shell: "hostnamectl set-hostname {{ fqdn }}"
  become: True

- name: "install_undercloud | set hostname --transient "
  shell: "hostnamectl --transient set-hostname {{ fqdn }}"
  become: True

- name: "install_undercloud |  Register rhel"
  shell: "subscription-manager register --force --org={{ myorg }} --activationkey={{ mykey }}"
  become: True

- name: "install_undercloud | attach pool "
  shell: "subscription-manager attach --pool={{ ostack_pool }}"
  become: True

- name: "install_undercloud | set release "
  shell: "sudo subscription-manager release --set={{ os_release }}"
  become: True

- name: "install_undercloud | ensure all is disabled "
  shell: "subscription-manager repos --disable=*"
  become: True

- name: "install_undercloud | enable needed repos "
  shell: "subscription-manager repos --enable=rhel-8-for-x86_64-baseos-eus-rpms --enable=rhel-8-for-x86_64-appstream-eus-rpms --enable=rhel-8-for-x86_64-highavailability-eus-rpms --enable=ansible-2.9-for-rhel-8-x86_64-rpms --enable=openstack-16.2-for-rhel-8-x86_64-rpms --enable=fast-datapath-for-rhel-8-x86_64-rpms"
  become: True

- name: "install_undercloud | disable container-tools"
  shell: "dnf module disable -y container-tools:rhel8"
  become: True

- name: "install_undercloud | enable enable container-tools:3.0"
  shell: "dnf module enable -y container-tools:3.0"
  become: True

- name: "install_undercloud | enable needed repos "
  shell: "dnf update -y"
  become: True

- name: "install_undercloud | enable needed repos "
  shell: "dnf install -y python3-tripleoclient"
  become: True